### ISSUE TITLE
Add name and title to metadata

### ISSUE THREAD

**Issue by napulen** [napulen/musicxml2dezrann#1]
Currently, the script writes the `date` and `producer` fields but not the `title` and `name`.

They could be extracted from the score.

Alternatively, they should also be able to be provided as optional arguments in the command line interface.

**Comment by juyaolongpaul** [comment]
What's the difference between `title` and `name`? I think one should be the file name, and the other one should be the actual name of the piece (if any)?

**Comment by napulen** [comment]
I have no idea. I think the example `json` files in Dezrann should give it away. So far, it seemed like title was the title of the piece and name was an arbitrary string.

**Comment by juyaolongpaul** [comment]
Yes. I will leave the name as empty now, or put `Harmony` to indicate it is a JSON file with chord labels.

**Comment by napulen** [comment]
I like the `annotation_type` as `name`. Thanks!
