### ISSUE TITLE
Formatting the output JSON file

### ISSUE THREAD

**Issue by juyaolongpaul** [napulen/musicxml2dezrann#4]
Currently, the output of the JSON file contains only one line where all the information is cramped. Need to separate `meta` and `labels`, and separate each annotation as a single line.

**Comment by napulen** [comment]
Maybe a `pprint` (pretty print) of the json string? I agree, a better formatted json would be better.

**Comment by juyaolongpaul** [comment]
I was looking for `pprint`, but later found that directly specifying `indent` in `json.dumps` got the job done very easily.
